In [1]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import numpy as np
import pandas as pd
from nltk.stem import WordNetLemmatizer

In [2]:
df = pd.read_csv('/content/spam.csv',encoding="ISO-8859-1")
df


v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [3]:
df.describe

<bound method NDFrame.describe of         v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        N

In [4]:
df.info

<bound method DataFrame.info of         v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN

In [5]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [6]:
df1 = df.copy()

In [7]:
df1 = df1.drop('Unnamed: 2',axis=1)
df1 = df1.drop('Unnamed: 3',axis=1)
df1 = df1.drop('Unnamed: 4',axis=1)

In [8]:
df1

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [9]:
df.v1.value_counts()

ham     4825
spam     747
Name: v1, dtype: int64

In [10]:
df1 ['spam'] = df1['v1'].apply(lambda x: 1 if x =='spam' else 0)

In [ ]:
def get(x) :
  if x == 'spam':
    return 1
  else :
    return 0

for i  in range(len(df.v1)):
  get(df.v1[i])


In [11]:
df1

v1                                                 v2  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0
...    ...                                                ...   ...
5567  spam  This is the 2nd time we have tried 2 contact u...     1
5568   ham              Will Ì_ b going to esplanade fr home?     0
5569   ham  Pity, * was in mood for that. So...any other s...     0
5570   ham  The guy did some bitching but I acted like i'd...     0
5571   ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [12]:
from sklearn.model_selection import train_test_split


In [17]:
x_train,x_test,y_train,y_test = train_test_split(df1.v2,df1.spam,test_size=0.2)

In [18]:
x_train[:4]


3464    Haha figures, well I found the piece and prisc...
3047             Die... Now i have e toot fringe again...
5453               Except theres a chick with huge boobs.
4936               G wants to know where the fuck you are
Name: v2, dtype: object

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [20]:
x_train_cv = cv.fit_transform(x_train.values)
x_train_cv

<4457x7688 sparse matrix of type '<class 'numpy.int64'>'
	with 59187 stored elements in Compressed Sparse Row format>

In [21]:
x_train_cv_np = x_train_cv.toarray()
x_train_cv_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [22]:
np.where(x_train_cv_np[0]!=0)  #gives index whre not zero

(array([ 949, 1448, 2848, 2976, 3296, 5179, 5384, 6764, 7390]),)

In [32]:
from sklearn.naive_bayes import MultinomialNB,GaussianNB
model = MultinomialNB()

In [24]:
model.fit(x_train_cv,y_train)

MultinomialNB()

In [25]:
x_test_cv = cv.fit_transform(x_test)

In [26]:
x_test_cv_np = x_test_cv.toarray()
x_test_cv_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [27]:
from sklearn.metrics import classification_report
from sklearn.pipeline import Pipeline

In [28]:
sentiment_model = Pipeline(
    steps=[
        (
            "count_verctorizer",CountVectorizer(stop_words='english')
        ),
        (
            "naive_bayes", MultinomialNB()
       )
])


In [29]:
sentiment_model.fit(x_train,y_train)

Pipeline(steps=[('count_verctorizer', CountVectorizer(stop_words='english')),
                ('naive_bayes', MultinomialNB())])

In [30]:
y_pred = sentiment_model.predict(x_test)

In [31]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       953
           1       0.95      0.96      0.95       162

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [33]:
sentiment_model2 = Pipeline(
    steps=[
        (
            "count_verctorizer",CountVectorizer(stop_words='english')
        ),
        (
            "naive_bayes", GaussianNB()
       )
])
